"""Mise a jour de conso

Revision ID: 0b5e8d5c3bed
Revises: 
Create Date: 2025-09-09 18:10:21.660085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5e8d5c3bed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('num_cnib', sa.String(), nullable=False),
    sa.Column('numero_abonne', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abonnes_id'), 'abonnes', ['id'], unique=False)
    op.create_index(op.f('ix_abonnes_num_cnib'), 'abonnes', ['num_cnib'], unique=True)
    op.create_index(op.f('ix_abonnes_numero_abonne'), 'abonnes', ['numero_abonne'], unique=True)
    op.create_index(op.f('ix_abonnes_tel'), 'abonnes', ['tel'], unique=True)
    op.create_table('lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_lignes_id'), 'lignes', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('techniciens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniciens_id'), 'techniciens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bornes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_pose', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_bornes_id'), 'bornes', ['id'], unique=False)
    op.create_table('consommations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abonne_id', sa.Integer(), nullable=False),
    sa.Column('mois_annee', sa.String(length=7), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consommations_id'), 'consommations', ['id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('abonne_id', sa.Integer(), nullable=True),
    sa.Column('ligne_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['abonnes.id'], ),
    sa.ForeignKeyConstraint(['ligne_id'], ['lignes.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_consommations_id'), table_name='consommations')
    op.drop_table('consommations')
    op.drop_index(op.f('ix_bornes_id'), table_name='bornes')
    op.drop_table('bornes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_techniciens_id'), table_name='techniciens')
    op.drop_table('techniciens')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_lignes_id'), table_name='lignes')
    op.drop_table('lignes')
    op.drop_index(op.f('ix_abonnes_tel'), table_name='abonnes')
    op.drop_index(op.f('ix_abonnes_numero_abonne'), table_name='abonnes')
    op.drop_index(op.f('ix_abonnes_num_cnib'), table_name='abonnes')
    op.drop_index(op.f('ix_abonnes_id'), table_name='abonnes')
    op.drop_table('abonnes')
    # ### end Alembic commands ###
