"""create all tables

Revision ID: 420f071261ae
Revises: 
Create Date: 2025-09-04 12:05:44.436253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420f071261ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('num_cnib', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_num_cnib'), 'clients', ['num_cnib'], unique=True)
    op.create_index(op.f('ix_clients_tel'), 'clients', ['tel'], unique=True)
    op.create_table('lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_lignes_id'), 'lignes', ['id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_table('techniciens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('specialite', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniciens_id'), 'techniciens', ['id'], unique=False)
    op.create_table('bornes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_pose', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_bornes_id'), 'bornes', ['id'], unique=False)
    op.create_table('compteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('calibre', sa.String(), nullable=True),
    sa.Column('index_initial', sa.Float(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_pose', sa.DateTime(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_index(op.f('ix_compteurs_id'), 'compteurs', ['id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('date_crea', sa.DateTime(), nullable=True),
    sa.Column('technicien_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('ligne_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['ligne_id'], ['lignes.id'], ),
    sa.ForeignKeyConstraint(['technicien_id'], ['techniciens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_id'), 'interventions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_compteurs_id'), table_name='compteurs')
    op.drop_table('compteurs')
    op.drop_index(op.f('ix_bornes_id'), table_name='bornes')
    op.drop_table('bornes')
    op.drop_index(op.f('ix_techniciens_id'), table_name='techniciens')
    op.drop_table('techniciens')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_lignes_id'), table_name='lignes')
    op.drop_table('lignes')
    op.drop_index(op.f('ix_clients_tel'), table_name='clients')
    op.drop_index(op.f('ix_clients_num_cnib'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
